export function renderHistoryPage() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Training History</title>
<style>
:root{color-scheme:dark;--bg:#080a0f;--panel:#121925;--text:#f4f7fb;--muted:#93a1b5;--line:#263245;--accent:#9be7c2}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.shell{width:min(920px,100%);margin:0 auto;padding:24px}header{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:22px}a{color:inherit;text-decoration:none}.button{border:1px solid var(--line);border-radius:999px;padding:10px 14px;background:rgba(255,255,255,.04)}h1{font-size:clamp(34px,8vw,70px);letter-spacing:-.06em;line-height:.9;margin:0}.muted{color:var(--muted)}.list{display:grid;gap:12px}.row{display:grid;grid-template-columns:1fr auto;gap:16px;padding:18px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(180deg,rgba(255,255,255,.07),rgba(255,255,255,.03))}.status{color:var(--accent);font-size:12px;letter-spacing:.13em;text-transform:uppercase}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:0 0 18px}.filters button{border:1px solid var(--line);border-radius:999px;padding:9px 12px;background:transparent;color:var(--text);cursor:pointer}.filters button.active{background:var(--accent);color:#07110d;border-color:var(--accent)}@media(max-width:640px){.shell{padding:18px}header{align-items:flex-start;flex-direction:column}.row{grid-template-columns:1fr}}
</style></head><body><main class="shell"><header><div><p class="muted">training generator</p><h1>History</h1></div><nav><a class="button" href="/">Home</a> <a class="button" href="/chat">Coach</a></nav></header><div class="filters"><button data-status="" class="active">All</button><button data-status="completed">Completed</button><button data-status="active">Active</button><button data-status="planned">Planned</button></div><section id="list" class="list"><p class="muted">Loading history…</p></section></main>
<script type="module">
const params = new URLSearchParams(location.search); const profileId = params.get('profile_id') || localStorage.getItem('trainingCoachProfile') || 'default'; let status = '';
const list = document.getElementById('list');
function apiUrl(path){ const url = new URL(path, location.href); url.username=''; url.password=''; return url; }
function escapeHtml(value){ return String(value ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
async function load(){ list.innerHTML='<p class="muted">Loading history…</p>'; const qs = new URLSearchParams({ profile_id: profileId, limit: '30' }); if(status) qs.set('status', status); const res = await fetch(apiUrl('/api/sessions?' + qs)); if(!res.ok){ list.innerHTML='<p class="muted">Could not load history.</p>'; return; } const data = await res.json(); const sessions = data.sessions || []; list.innerHTML = sessions.length ? sessions.map(s => '<a class="row" href="/sessions/' + encodeURIComponent(s.id) + '"><span><strong>' + escapeHtml(s.title) + '</strong><br><span class="muted">' + escapeHtml(s.summary || ((s.exercise_count || 0) + ' exercises')) + '</span></span><span class="status">' + escapeHtml(s.status) + '</span></a>').join('') : '<p class="muted">No sessions found.</p>'; }
document.querySelectorAll('[data-status]').forEach(btn => btn.addEventListener('click', () => { status = btn.dataset.status; document.querySelectorAll('[data-status]').forEach(b => b.classList.toggle('active', b === btn)); load(); })); load();
</script></body></html>`;
}
